name: Publish (GitHub releases)

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Get mod version from Gradle
        uses: madhead/read-java-properties@latest
        id: mod_version
        with:
          file: gradle.properties
          property: mod_version
          default: 0.0.1

      - name: Get supported Minecraft version from Gradle
        uses: madhead/read-java-properties@latest
        id: supported_minecraft_version
        with:
          file: gradle.properties
          property: supported_minecraft_version
          default: 0.0.1

      - run: echo version string ${{ steps.mod_version.outputs.value }}+mc${{ steps.supported_minecraft_version.outputs.value }}

      - name: Setup JDK (Temurin 17)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Change Gradle wrapper permissions
        run: chmod +x ./gradlew

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Publish mod to GitHub releases
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "**/build/libs/!(*-@(dev-shadow|transformProduction*).jar)"
          bodyFile: CHANGELOG_LATEST.md
